// ============================================================================
// ROADGUARD DATABASE & DOMAIN TYPES
// Aligned with Supabase PostgreSQL 15+ Schema
// ============================================================================

export type UserRole = 'citizen' | 'admin';

export type HazardType =
  | 'pothole'
  | 'broken_traffic_signal'
  | 'poor_street_lighting'
  | 'unsafe_pedestrian_crossing'
  | 'road_damage'
  | 'waterlogging'
  | 'obstruction'
  | 'other';

export type SeverityLevel = 'minor' | 'moderate' | 'severe' | 'catastrophic';

export type TrafficExposureLevel = 'low' | 'medium' | 'high' | 'arterial';

export type VulnerabilityZone =
  | 'standard'
  | 'transit_hub'
  | 'hospital_zone'
  | 'school_zone';

export type PriorityLevel = 'low' | 'medium' | 'high' | 'critical';

export type ReportStatus =
  | 'submitted'
  | 'under_review'
  | 'in_progress'
  | 'resolved'
  | 'rejected';

export interface PriorityFactorDetail {
  factor: string;
  score: number;
  maxScore: number;
  detail: string;
  rationale: string;
}

export interface PriorityBreakdown {
  total_score: number;
  priority_level: PriorityLevel;
  calculated_at: string;
  factors: PriorityFactorDetail[];
}

export interface AISuggestion {
  suggested_hazard: HazardType;
  confidence: 'low' | 'medium' | 'high';
  confidence_percentage: number;
  notes: string;
  detected_features?: string[];
  is_assistive: boolean;
}

// ----------------------------------------------------------------------------
// 1. RAW POSTGRESQL ROW SCHEMAS (As stored in Database)
// ----------------------------------------------------------------------------

export interface ProfileRow {
  id: string; // UUID references auth.users(id)
  full_name: string;
  role: UserRole;
  phone: string | null;
  department: string | null;
  created_at: string;
  updated_at: string;
}

export interface ReportRow {
  id: string; // UUID primary key
  report_code: string; // RG-YYYY-XXXX
  user_id: string | null; // UUID references profiles(id)
  hazard_type: HazardType;
  location_name: string;
  latitude: number;
  longitude: number;
  description: string;
  severity: SeverityLevel;
  traffic_exposure: TrafficExposureLevel;
  vulnerability_level: VulnerabilityZone;
  priority_score: number;
  priority_level: PriorityLevel;
  priority_breakdown: PriorityBreakdown;
  status: ReportStatus;
  image_url: string | null;
  ai_suggestion: AISuggestion | null;
  created_at: string;
  updated_at: string;
  resolved_at?: string | null;
}


export interface ReportUpdateRow {
  id: string; // UUID primary key
  report_id: string; // UUID references reports(id)
  admin_id: string | null; // UUID references profiles(id)
  previous_status: ReportStatus | null;
  new_status: ReportStatus;
  comment: string;
  created_at: string;
}

// ----------------------------------------------------------------------------
// 2. INSERT & UPDATE PAYLOADS (Strictly matches writable database columns)
// ----------------------------------------------------------------------------

export interface ReportInsertPayload {
  // id & report_code are generated server-side by PostgreSQL
  user_id?: string | null;
  hazard_type: HazardType;
  location_name: string;
  latitude: number;
  longitude: number;
  description: string;
  severity: SeverityLevel;
  traffic_exposure: TrafficExposureLevel;
  vulnerability_level: VulnerabilityZone;
  priority_score: number;
  priority_level: PriorityLevel;
  priority_breakdown: PriorityBreakdown;
  status?: ReportStatus;
  image_url?: string | null;
  ai_suggestion?: AISuggestion | null;
}

export interface ReportUpdateInsertPayload {
  // id is generated by PostgreSQL
  report_id: string;
  admin_id?: string | null;
  previous_status?: ReportStatus | null;
  new_status: ReportStatus;
  comment: string;
}

// ----------------------------------------------------------------------------
// 3. JOINED / DOMAIN MODELS (For UI rendering with joined profile metadata)
// ----------------------------------------------------------------------------

export interface ProfileRecord extends ProfileRow {}

export interface ReportRecord extends ReportRow {
  // Joined or client-cached metadata
  user_name?: string | null;
  is_demo?: boolean;
}

export interface ReportUpdateRecord extends ReportUpdateRow {
  // Joined or client-cached admin metadata
  admin_name?: string | null;
  department?: string | null;
}
